name: prod

on:
  push:
    branches:
      - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-repository: [powerfulyang/powerfulyang.com]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: prod.Dockerfile
          push: true
          tags: ${{ matrix.docker-repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
      -
        name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            docker pull ${{ matrix.docker-repository }}
            cd ~/applications
            docker-compose up -d --force-recreate powerfulyang.com
            docker image prune -a -f
